### ISSUE TITLE
Problem with latest compiled CloudFormationResourceSpecification.json

### ISSUE THREAD

**Issue by kbessas** [awslabs/goformation#105]
There are 2 discrepancies between the latest generated CloudFormationResourceSpecification and the CF docs.

Please see my 2 comment on https://github.com/awslabs/goformation/pull/104

**Comment by PaulMaddox** [comment]
Good catch - this looks like a discrepancy between the [AWS CloudFormation Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) published by the CloudFormation team, and their [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html#cfn-ec2-vpcendpoint-privatednsenabled)/the [CreateVpcEndpoint API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcEndpoint.html). 

As goformation is automatically generated from the published resource specification, it has also picked this up. I have reached out the the CloudFormation team via internal channels to report this  so that it can be fixed upstream.

**Comment by PaulMaddox** [comment]
We now have a workaround for this in goformation until the official schema is updated by the CloudFormation team.
