### ISSUE TITLE
Allow unknown fields on AWS::CloudFormation::CustomResource

### ISSUE THREAD

**Issue by jarreds** [awslabs/goformation#193]
Dynamic fields are par for the course in `AWS::CloudFormation::CustomResource`.

**Comment by toddobryan-clever** [comment]
It would also be nice if there were a way to use the `Custom::String` type instead of `AWS::CloudFormation::CustomResource`. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html#aws-cfn-resource-type-name

I've included this here since I think these two could probably be fixed in one code block, but I'm happy to create another ticket if that would help.

**Comment by mweagle** [comment]
I would also like to see support for custom fields and `Custom::String` .
