### ISSUE TITLE
EFS AuthorizationConfig type is not generated

### ISSUE THREAD

**Issue by ndeloof** [awslabs/goformation#327]
see https://github.com/awslabs/goformation/blob/master/cloudformation/ecs/aws-ecs-taskdefinition_efsvolumeconfiguration.go#L14

should be generated as an `AuthorizationConfig` type matching https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-efsvolumeconfiguration.html#cfn-ecs-taskdefinition-efsvolumeconfiguration-authorizationconfig

**Comment by PaulMaddox** [comment]
This is occurring because the `AuthorizationConfig` property has been defined in the [AWS CloudFormation Resource Specification](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) as having two types (the correct `Type: AuthorizationConfig` as well as the incorrect `PrimitiveType: Json`).

```json
        "AuthorizationConfig": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-efsvolumeconfiguration.html#cfn-ecs-taskdefinition-efsvolumeconfiguration-authorizationconfig",
          "UpdateType": "Immutable",
          "Required": false,
          "PrimitiveType": "Json",
          "Type": "AuthorizationConfig"
        }
```

**Comment by rubenfonseca** [comment]
This was fixed a couple of days ago here https://github.com/awslabs/goformation/pull/422. Closing.
