### ISSUE TITLE
failed to open json file from the examples valid-template-resource-attributes

### ISSUE THREAD

**Issue by YotamWolbrum** [awslabs/goformation#380]
Hi all,
I tried to open the file " valid-template-resource-attributes" from your test folder with goformation.

I'm getting the following error : 
ERROR: json: cannot unmarshal string into Go struct field ResourceSignal.CreationPolicy.ResourceSignal.Count of type float64

and I can see in the json file this element : 
        "ResourceSignal": {
          "Count": "3",
          "Timeout": "PT15M"
        }

tried to use it on aws console and succeeded.

Thanks a lot

**Comment by PaulMaddox** [comment]
Hi @YotamWolbrum. 

The field `Count` is described in the CloudFormation Specification as a `Number` field. 
See this page: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html

That means that within goformation, it will be described as an Go number format (float64 in this case).

In order to use this within goformation, your template will need to remove the quoting from the number. 
E.g.

```json
"ResourceSignal": {
    "Count": 3,
    "Timeout": "PT15M"
}
````

Strictly speaking, the original template should use a number (as above), however your original example works in the CloudFormation console, as the CloudFormation service is not as strict with regards to types. One of the main benefits of goformation, is the typing. Unfortunately there's no easy way to make goformation less strict without greatly reducing the value of this library.

**Comment by SleepyBrett** [comment]
I'm sorry to see this closed, we were trying to use this library to verify some tagging requirements. But it can't parse most of our CF templates that are valid according to the api.
