### ISSUE TITLE
Vulnerability CVE-2022-3064

### ISSUE THREAD

**Issue by hiltol** [awslabs/goformation#534]
Hi, our scans detected https://github.com/advisories/GHSA-6q6q-88xp-6f2r in the github.com/sanathkr/go-yaml module which hasn't been updated in 5 years. The suggested fix is to upgrade to [go-yaml](https://github.com/go-yaml/yaml) > 2.2.4.

**Comment by rubenfonseca** [comment]
Thank you for your message. As far as I understand, we're not using go-yaml <= 2.2.4. Please feel free to re-open if you disagree.

**Comment by balazs-marjan** [comment]
Hi, @rubenfonseca 

So this dependency of yours `github.com/sanathkr/go-yaml` is actually an old fork of the `go-yaml` library, right?. Some scanning tools - like `https://www.mend.io/`'s solution - can detect forks like this.

The concern is obvious, any vulnerability found in the original library since the time of the fork remains unaddressed.

**Comment by hiltol** [comment]
Thank you!
